# Generated by Django 5.1.4 on 2025-01-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doodle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doodle_data', models.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='doodle/')),
            ],
            options={
                'verbose_name': 'Doodle',
                'verbose_name_plural': 'Doodles',
                'ordering': ['-created_at'],
            },
        ),
    ]
