# Generated by Django 5.1.4 on 2025-01-02 02:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doodle', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoodlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('max_width', models.IntegerField(default=800, help_text='Canvas width in pixels')),
                ('max_height', models.IntegerField(default=600, help_text='Canvas height in pixels')),
            ],
            options={
                'verbose_name': 'Doodle Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
