# Generated by Django 5.0.4 on 2024-06-07 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionIndexPage',
        ),
    ]
