# Generated by Django 5.0.4 on 2024-06-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_delete_collectionindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='desginer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
