# Generated by Django 5.0.4 on 2024-06-09 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_alter_product_brand_alter_product_desginer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desginer',
            new_name='designer',
        ),
    ]
