# Generated by Django 5.0.4 on 2024-05-05 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestbookpage",
            name="from_address",
        ),
        migrations.RemoveField(
            model_name="guestbookpage",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="guestbookpage",
            name="to_address",
        ),
    ]
