# Generated by Django 5.1.4 on 2025-01-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestbookentry',
            options={'verbose_name_plural': 'Guestbook entries'},
        ),
    ]
