# Generated by Django 5.0.4 on 2024-05-08 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customimage_caption'),
        ('blog', '0003_blogtagindexpage_remove_blogindexpage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.customimage'),
        ),
    ]
