# Generated by Django 5.0.4 on 2024-05-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='authors',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='authors',
            field=models.CharField(default='Acy', max_length=250),
            preserve_default=False,
        ),
    ]
