# Generated by Django 5.0.4 on 2024-05-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpage_authors_blogpage_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='authors',
        ),
    ]
