# Generated by Django 5.0.4 on 2024-05-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogpage_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
