# Generated by Django 5.0.4 on 2024-05-23 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_delete_blogcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="categories",
        ),
        migrations.DeleteModel(
            name="BlogCategory",
        ),
    ]
