# Generated by Django 5.0.4 on 2024-05-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_remove_blogpage_categories_delete_blogcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="caption",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
