# Generated by Django 5.1.2 on 2024-10-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askboxpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='AskBoxPage',
        ),
    ]
