# Generated by Django 5.1.2 on 2024-10-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askbox', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='Anon', max_length=255),
            preserve_default=False,
        ),
    ]
