# Generated by Django 5.0.4 on 2024-05-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
