# Generated by Django 5.0.4 on 2024-05-28 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_remove_normalpage_image_alter_normalpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
        migrations.DeleteModel(
            name="FormPage",
        ),
    ]
