# Generated by Django 5.0.4 on 2024-05-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_designsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsettings',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Square suggested.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.customimage'),
        ),
    ]
