# Generated by Django 5.0.4 on 2024-06-09 21:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_normalpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
