# Generated by Django 5.1.4 on 2024-12-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_genericindexpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='customdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
