# Generated by Django 5.1.4 on 2024-12-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_customimage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='caption',
        ),
    ]
