# Generated by Django 5.1.4 on 2024-12-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_customimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
